services:
  broker:
    image: apache/kafka:latest
    container_name: kafka
    environment:
      KAFKA_NODE_ID: ${KAFKA_NODE_ID}
      KAFKA_PROCESS_ROLES: ${KAFKA_PROCESS_ROLES}
      KAFKA_LISTENERS: ${KAFKA_LISTENERS}
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS}
      KAFKA_CONTROLLER_LISTENER_NAMES: ${KAFKA_CONTROLLER_LISTENER_NAMES}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: ${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}
      KAFKA_CONTROLLER_QUORUM_VOTERS: ${KAFKA_CONTROLLER_QUORUM_VOTERS}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: ${KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR}
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: ${KAFKA_TRANSACTION_STATE_LOG_MIN_ISR}
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: ${KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS}
      KAFKA_NUM_PARTITIONS: ${KAFKA_NUM_PARTITIONS}

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./0-nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user-service
      - wallet-service

  user-service:
    container_name: user-service
    build: ./1-users
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_INTERNAL_PORT}"
    depends_on:
      - broker
      - user-redis
    environment:
      - USER_REDIS_PASSWORD=${USER_REDIS_PASSWORD}
      - USER_REDIS_PORT=${USER_REDIS_PORT}
      - ENVIRONMENT=${ENVIRONMENT}
      - MODE=${MODE}

  wallet-service:
    container_name: wallet-service
    build: ./3-wallet
    ports:
      - "${WALLET_SERVICE_PORT}:${WALLET_SERVICE_INTERNAL_PORT}"
    depends_on:
      - broker
      - wallet-redis
    environment:
      - WALLET_REDIS_PASSWORD=${WALLET_REDIS_PASSWORD}
      - WALLET_REDIS_PORT=${WALLET_REDIS_PORT}

  user-redis:
    image: redis:alpine
    container_name: user-redis
    ports:
      - "${USER_REDIS_PORT}:6379"
    volumes:
      - user_redis_data:/data
    restart: always
    command: redis-server --appendonly yes --requirepass ${USER_REDIS_PASSWORD}

  wallet-redis:
    image: redis:alpine
    container_name: wallet-redis
    ports:
      - "${WALLET_REDIS_PORT}:6379"
    volumes:
      - wallet_redis_data:/data
    restart: always
    command: redis-server --appendonly yes --requirepass ${WALLET_REDIS_PASSWORD}

volumes:
  user_redis_data:
  wallet_redis_data:
